import type { Test } from '../model/types';

export const tests: Test[] = [
  {
    id: 'js-basics-types',
    title: 'JS Basics: Types & Coercion',
    description: 'Basic types, type coercion, typeof, comparisons, and language quirks.',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/5968/5968292.png',
    questionCount: 10,
    questions: [
      {
        id: 1,
        order: 1,
        type: 'quiz',
        question: 'What does typeof null return?',
        options: ['null', 'undefined', 'object', 'NaN'],
        correctIndex: 2,
      },
      {
        id: 2,
        order: 2,
        type: 'quiz',
        question: 'What does typeof NaN return?',
        options: ['number', 'NaN', 'undefined', 'object'],
        correctIndex: 0,
      },
      {
        id: 3,
        order: 3,
        type: 'quiz',
        question: "What is the result of: '5' - 2 ?",
        options: ["'3'", '3', 'NaN', "'52'"],
        correctIndex: 1,
      },
      {
        id: 4,
        order: 4,
        type: 'quiz',
        question: "What is the result of: '5' + 2 ?",
        options: ['7', "'7'", "'52'", 'NaN'],
        correctIndex: 2,
      },
      {
        id: 5,
        order: 5,
        type: 'quiz',
        question: 'What is the result of: 0 == false ?',
        options: ['true', 'false', 'TypeError', 'undefined'],
        correctIndex: 0,
      },
      {
        id: 6,
        order: 6,
        type: 'quiz',
        question: 'What is the result of: 0 === false ?',
        options: ['true', 'false', 'TypeError', 'undefined'],
        correctIndex: 1,
      },
      {
        id: 7,
        order: 7,
        type: 'quiz',
        question: "What does Boolean('0') return?",
        options: ['false', 'true', '0', 'NaN'],
        correctIndex: 1,
      },
      {
        id: 8,
        order: 8,
        type: 'quiz',
        question: 'What is the result of: [] == ![] ?',
        options: ['true', 'false', 'TypeError', 'undefined'],
        correctIndex: 0,
      },
      {
        id: 9,
        order: 9,
        type: 'quiz',
        question: "What is the result of: Number('') ?",
        options: ['0', 'NaN', "''", 'undefined'],
        correctIndex: 0,
      },
      {
        id: 10,
        order: 10,
        type: 'quiz',
        question: 'What is the type of BigInt(10)?',
        options: ['number', 'bigint', 'object', 'symbol'],
        correctIndex: 1,
      },
    ],
  },

  {
    id: 'js-scope-closures',
    title: 'JS Core: Scope & Closures',
    description: 'Scopes, var/let/const, closures, and common pitfalls.',
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSoeSPeFL9c7g3IbrfY09-hir8Jki-fBXYkg&s',
    questionCount: 10,
    questions: [
      {
        id: 11,
        order: 1,
        type: 'quiz',
        question: 'What is the key difference between let and var?',
        options: [
          'let has block scope, var has function scope',
          'var cannot be reassigned, let can',
          'let is hoisted, var is not',
          'var exists only inside if/for blocks',
        ],
        correctIndex: 0,
      },
      {
        id: 12,
        order: 2,
        type: 'quiz',
        question: 'What happens if you access a let variable before its declaration?',
        options: [
          'Returns undefined',
          'Throws ReferenceError (TDZ)',
          'Returns null',
          'Throws TypeError',
        ],
        correctIndex: 1,
      },
      {
        id: 13,
        order: 3,
        type: 'quiz',
        question:
          'What will the code output?\nfor (var i=0;i<3;i++) setTimeout(()=>console.log(i),0)',
        options: ['0 1 2', '1 2 3', '3 3 3', 'undefined undefined undefined'],
        correctIndex: 2,
      },
      {
        id: 14,
        order: 4,
        type: 'quiz',
        question:
          'What will the code output?\nfor (let i=0;i<3;i++) setTimeout(()=>console.log(i),0)',
        options: ['0 1 2', '3 3 3', '1 2 3', 'undefined undefined undefined'],
        correctIndex: 0,
      },
      {
        id: 15,
        order: 5,
        type: 'quiz',
        question: 'What is a closure?',
        options: [
          'A function with access to variables from its outer scope',
          'Any function with a return statement',
          'Syntax for private class fields',
          'An object property for storing methods',
        ],
        correctIndex: 0,
      },
      {
        id: 16,
        order: 6,
        type: 'quiz',
        question: 'Can you change the value of a const variable?',
        options: [
          'Never',
          'Yes, if it is an object and its properties are changed',
          'Only in strict mode',
          'Only inside functions',
        ],
        correctIndex: 1,
      },
      {
        id: 17,
        order: 7,
        type: 'quiz',
        question: 'What does typeof return for a function?',
        options: ['function', 'object', 'callable', 'method'],
        correctIndex: 0,
      },
      {
        id: 18,
        order: 8,
        type: 'quiz',
        question: 'What scope does a let variable have inside an if block?',
        options: ['Global', 'Function', 'Block (only inside the if block)', 'Prototype'],
        correctIndex: 2,
      },
      {
        id: 19,
        order: 9,
        type: 'quiz',
        question:
          'What happens if you use an undeclared variable inside a function (in strict mode)?',
        options: [
          'A global variable is created',
          'Throws ReferenceError',
          'Throws TypeError',
          'Returns undefined',
        ],
        correctIndex: 1,
      },
      {
        id: 20,
        order: 10,
        type: 'quiz',
        question: 'What does hoisting mean in JS?',
        options: [
          'Moving declarations (not initializations) to the top of the scope',
          'Automatic type conversion',
          'Faster loop execution',
          'Prohibition of using var',
        ],
        correctIndex: 0,
      },
    ],
  },

  {
    id: 'js-objects-this-prototype',
    title: 'JS Objects: this, Prototype, Classes',
    description: 'The this context, methods, bind/call/apply, prototypes, and class basics.',
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSlKGWQNw9SzJsAcQn7gisfnwGESGyS1qyyw&s',
    questionCount: 10,
    questions: [
      {
        id: 21,
        order: 1,
        type: 'quiz',
        question: 'What is this in a regular function call fn() in strict mode?',
        options: ['window', 'global', 'undefined', 'the function fn itself'],
        correctIndex: 2,
      },
      {
        id: 22,
        order: 2,
        type: 'quiz',
        question: 'Which method creates a new function with permanently bound this?',
        options: ['call', 'apply', 'bind', 'assign'],
        correctIndex: 2,
      },
      {
        id: 23,
        order: 3,
        type: 'quiz',
        question: 'What is the difference between call and apply?',
        options: [
          'call takes arguments as a list, apply takes an array',
          'apply is faster than call',
          'call works only with object methods',
          'apply cannot be used with this',
        ],
        correctIndex: 0,
      },
      {
        id: 24,
        order: 4,
        type: 'quiz',
        question: 'What is a prototype in JS?',
        options: [
          'An inheritance mechanism via object chains',
          'A data type for functions',
          'Syntax for private fields',
          'A built-in Node.js module',
        ],
        correctIndex: 0,
      },
      {
        id: 25,
        order: 5,
        type: 'quiz',
        question: 'Where is the prototype of constructor functions stored?',
        options: [
          'constructor.__proto__',
          'constructor.prototype',
          'object.prototype',
          'Function.__proto__',
        ],
        correctIndex: 1,
      },
      {
        id: 26,
        order: 6,
        type: 'quiz',
        question: 'What does ({}) instanceof Object return?',
        options: ['true', 'false', 'TypeError', 'undefined'],
        correctIndex: 0,
      },
      {
        id: 27,
        order: 7,
        type: 'quiz',
        question: 'How to create an object with null prototype?',
        options: [
          'new Object(null)',
          'Object.create(null)',
          '{}.create(null)',
          'Object.setPrototypeOf({}, null)',
        ],
        correctIndex: 1,
      },
      {
        id: 28,
        order: 8,
        type: 'quiz',
        question: 'What happens when accessing a property not in the object but in its prototype?',
        options: [
          'Returns undefined',
          'Throws TypeError',
          'Finds the property in the prototype chain',
          'Creates the property automatically',
        ],
        correctIndex: 2,
      },
      {
        id: 29,
        order: 9,
        type: 'quiz',
        question: 'How does arrow function differ in terms of this?',
        options: [
          'It has its own this like regular functions',
          'It takes this from the outer scope (lexically)',
          'It is always bound to window',
          'Its this is always undefined',
        ],
        correctIndex: 1,
      },
      {
        id: 30,
        order: 10,
        type: 'quiz',
        question: 'What does the new operator do?',
        options: [
          'Creates an object, links prototype, calls function with this and returns the object',
          'Only calls the function',
          'Creates a class at runtime',
          'Copies properties from prototype',
        ],
        correctIndex: 0,
      },
    ],
  },

  {
    id: 'js-arrays-methods',
    title: 'JS Arrays: Methods & Mutation',
    description: 'Array methods, mutation, map/filter/reduce, sorting and comparison.',
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjSwhVCJ_gVltd2jd559Z2gGUyRMwmC_YCIQ&s',
    questionCount: 10,
    questions: [
      {
        id: 31,
        order: 1,
        type: 'quiz',
        question: 'Which method creates a new array without modifying the original?',
        options: ['push', 'splice', 'map', 'sort'],
        correctIndex: 2,
      },
      {
        id: 32,
        order: 2,
        type: 'quiz',
        question: 'Which method mutates the original array?',
        options: ['filter', 'concat', 'slice', 'splice'],
        correctIndex: 3,
      },
      {
        id: 33,
        order: 3,
        type: 'quiz',
        question: 'What does [].length return?',
        options: ['0', 'null', 'undefined', '1'],
        correctIndex: 0,
      },
      {
        id: 34,
        order: 4,
        type: 'quiz',
        question: 'What does [1,2,3].reduce((acc,x)=>acc+x, 0) return?',
        options: ['6', '3', '0', 'TypeError'],
        correctIndex: 0,
      },
      {
        id: 35,
        order: 5,
        type: 'quiz',
        question: 'What does Array.isArray(value) do?',
        options: [
          'Checks if value is an array',
          'Converts value to an array',
          'Checks if value is an object',
          'Compares two arrays',
        ],
        correctIndex: 0,
      },
      {
        id: 36,
        order: 6,
        type: 'quiz',
        question: 'How to correctly sort numbers in ascending order?',
        options: [
          '[10,2,1].sort()',
          '[10,2,1].sort((a,b)=>a-b)',
          '[10,2,1].sort((a,b)=>b-a)',
          '[10,2,1].sort(Number)',
        ],
        correctIndex: 1,
      },
      {
        id: 37,
        order: 7,
        type: 'quiz',
        question: 'What does [1,2,3].includes(2) return?',
        options: ['true', 'false', '2', 'undefined'],
        correctIndex: 0,
      },
      {
        id: 38,
        order: 8,
        type: 'quiz',
        question: 'What is the difference between slice and splice?',
        options: [
          'slice mutates the array, splice does not',
          'splice mutates and can remove/insert elements, slice does not mutate and returns a copy',
          'slice works only with strings',
          'splice returns index, slice returns boolean',
        ],
        correctIndex: 1,
      },
      {
        id: 39,
        order: 9,
        type: 'quiz',
        question: 'What does [1,2,3].find(x => x > 1) return?',
        options: ['2', '[2,3]', 'true', '1'],
        correctIndex: 0,
      },
      {
        id: 40,
        order: 10,
        type: 'quiz',
        question: 'What does [1,2,3].every(x => x > 0) return?',
        options: ['true', 'false', '1', 'undefined'],
        correctIndex: 0,
      },
    ],
  },

  {
    id: 'js-async-event-loop',
    title: 'JS Async: Promises & Event Loop',
    description: 'Task queues, microtasks/macrotasks, Promises, async/await, and timers.',
    imageUrl:
      'https://avatars.mds.yandex.net/i?id=4ad92aec5b81d2181fa555dd16d28daf578da1d7-9211697-images-thumbs&n=13',
    questionCount: 10,
    questions: [
      {
        id: 41,
        order: 1,
        type: 'quiz',
        question: 'What does an async function always return?',
        options: ['Promise', 'number', 'callback', 'undefined'],
        correctIndex: 0,
      },
      {
        id: 42,
        order: 2,
        type: 'quiz',
        question: 'Which queue runs first: microtasks or macrotasks?',
        options: ['macrotasks', 'microtasks', 'simultaneously', 'depends on browser'],
        correctIndex: 1,
      },
      {
        id: 43,
        order: 3,
        type: 'quiz',
        question: 'What happens when calling Promise.resolve(5)?',
        options: [
          'Creates a rejected promise',
          'Creates a resolved promise with value 5',
          'Blocks the thread',
          'Returns 5 without a promise',
        ],
        correctIndex: 1,
      },
      {
        id: 44,
        order: 4,
        type: 'quiz',
        question: 'What does await do?',
        options: [
          'Stops all JS execution',
          'Waits for a promise inside an async function',
          'Makes the function synchronous',
          'Cancels a promise',
        ],
        correctIndex: 1,
      },
      {
        id: 45,
        order: 5,
        type: 'quiz',
        question:
          'What will the code output?\nconsole.log(1); setTimeout(()=>console.log(2),0); console.log(3);',
        options: ['1 2 3', '1 3 2', '2 1 3', '3 1 2'],
        correctIndex: 1,
      },
      {
        id: 46,
        order: 6,
        type: 'quiz',
        question:
          'What will the code output?\nconsole.log(1); Promise.resolve().then(()=>console.log(2)); console.log(3);',
        options: ['1 2 3', '1 3 2', '2 1 3', '3 1 2'],
        correctIndex: 1,
      },
      {
        id: 47,
        order: 7,
        type: 'quiz',
        question: 'How do you catch a promise error?',
        options: ['.catch()', '.error()', '.fail()', 'try/catch without await'],
        correctIndex: 0,
      },
      {
        id: 48,
        order: 8,
        type: 'quiz',
        question: 'What does Promise.all do?',
        options: [
          'Returns the first resolved promise',
          'Waits for all promises or fails on first reject',
          'Executes promises sequentially',
          'Cancels all promises',
        ],
        correctIndex: 1,
      },
      {
        id: 49,
        order: 9,
        type: 'quiz',
        question: 'What does Promise.race do?',
        options: [
          'Waits for all promises',
          'Returns the result of the first settled promise (resolve/reject)',
          'Sorts promises by time',
          'Always returns resolve',
        ],
        correctIndex: 1,
      },
      {
        id: 50,
        order: 10,
        type: 'quiz',
        question: 'Where does a .then() callback execute relative to setTimeout(…, 0)?',
        options: [
          'After setTimeout',
          'Before setTimeout (microtask runs before macrotask)',
          'At the same time',
          'Depends on number of promises',
        ],
        correctIndex: 1,
      },
    ],
  },
];
