import type { Test } from '../model/types';

export const tests: Test[] = [
  {
    id: 'js-basics-types',
    title: 'JS Basics: Types & Coercion',
    description: 'Базовые типы, преобразования, typeof, сравнения и странности языка.',
    imageUrl: 'https://cdn-icons-png.flaticon.com/512/5968/5968292.png',
    questionCount: 10,
    questions: [
      {
        id: 1,
        order: 1,
        type: 'quiz',
        question: 'Что вернёт typeof null?',
        options: ['null', 'undefined', 'object', 'NaN'],
        correctIndex: 2,
      },
      {
        id: 2,
        order: 2,
        type: 'quiz',
        question: 'Что вернёт typeof NaN?',
        options: ['number', 'NaN', 'undefined', 'object'],
        correctIndex: 0,
      },
      {
        id: 3,
        order: 3,
        type: 'quiz',
        question: "Чему равно выражение: '5' - 2 ?",
        options: ["'3'", '3', 'NaN', "'52'"],
        correctIndex: 1,
      },
      {
        id: 4,
        order: 4,
        type: 'quiz',
        question: "Чему равно выражение: '5' + 2 ?",
        options: ['7', "'7'", "'52'", 'NaN'],
        correctIndex: 2,
      },
      {
        id: 5,
        order: 5,
        type: 'quiz',
        question: 'Чему равно: 0 == false ?',
        options: ['true', 'false', 'TypeError', 'undefined'],
        correctIndex: 0,
      },
      {
        id: 6,
        order: 6,
        type: 'quiz',
        question: 'Чему равно: 0 === false ?',
        options: ['true', 'false', 'TypeError', 'undefined'],
        correctIndex: 1,
      },
      {
        id: 7,
        order: 7,
        type: 'quiz',
        question: "Что вернёт Boolean('0') ?",
        options: ['false', 'true', '0', 'NaN'],
        correctIndex: 1,
      },
      {
        id: 8,
        order: 8,
        type: 'quiz',
        question: 'Чему равно: [] == ![] ?',
        options: ['true', 'false', 'TypeError', 'undefined'],
        correctIndex: 0,
      },
      {
        id: 9,
        order: 9,
        type: 'quiz',
        question: "Чему равно: Number('') ?",
        options: ['0', 'NaN', "''", 'undefined'],
        correctIndex: 0,
      },
      {
        id: 10,
        order: 10,
        type: 'quiz',
        question: 'Какой тип у значения BigInt(10)?',
        options: ['number', 'bigint', 'object', 'symbol'],
        correctIndex: 1,
      },
    ],
  },

  {
    id: 'js-scope-closures',
    title: 'JS Core: Scope & Closures',
    description: 'Области видимости, var/let/const, замыкания и типичные ловушки.',
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSoeSPeFL9c7g3IbrfY09-hir8Jki-fBXYkg&s',
    questionCount: 10,
    questions: [
      {
        id: 11,
        order: 1,
        type: 'quiz',
        question: 'В чём ключевая разница между let и var?',
        options: [
          'let имеет блочную область видимости, var — функциональную',
          'var нельзя переопределять, let можно',
          'let всплывает (hoisting), var нет',
          'var существует только в блоках if/for',
        ],
        correctIndex: 0,
      },
      {
        id: 12,
        order: 2,
        type: 'quiz',
        question: 'Что произойдёт при обращении к let-переменной до её объявления?',
        options: [
          'Вернёт undefined',
          'Выбросит ReferenceError (TDZ)',
          'Вернёт null',
          'Выбросит TypeError',
        ],
        correctIndex: 1,
      },
      {
        id: 13,
        order: 3,
        type: 'quiz',
        question: 'Что выведет код?\nfor (var i=0;i<3;i++) setTimeout(()=>console.log(i),0)',
        options: ['0 1 2', '1 2 3', '3 3 3', 'undefined undefined undefined'],
        correctIndex: 2,
      },
      {
        id: 14,
        order: 4,
        type: 'quiz',
        question: 'Что выведет код?\nfor (let i=0;i<3;i++) setTimeout(()=>console.log(i),0)',
        options: ['0 1 2', '3 3 3', '1 2 3', 'undefined undefined undefined'],
        correctIndex: 0,
      },
      {
        id: 15,
        order: 5,
        type: 'quiz',
        question: 'Что такое замыкание (closure)?',
        options: [
          'Функция вместе с доступом к переменным из внешней области видимости',
          'Любая функция с return',
          'Синтаксис для приватных полей класса',
          'Свойство объекта для хранения методов',
        ],
        correctIndex: 0,
      },
      {
        id: 16,
        order: 6,
        type: 'quiz',
        question: 'Можно ли изменить значение переменной, объявленной через const?',
        options: [
          'Никогда нельзя',
          'Можно, если это объект и меняются его свойства',
          'Можно только в strict mode',
          'Можно только в функциях',
        ],
        correctIndex: 1,
      },
      {
        id: 17,
        order: 7,
        type: 'quiz',
        question: 'Что вернёт typeof для функции?',
        options: ['function', 'object', 'callable', 'method'],
        correctIndex: 0,
      },
      {
        id: 18,
        order: 8,
        type: 'quiz',
        question: 'Какая область видимости у переменной, объявленной внутри блока if с let?',
        options: [
          'Глобальная',
          'Функциональная',
          'Блочная (только внутри if-блока)',
          'Прототипная',
        ],
        correctIndex: 2,
      },
      {
        id: 19,
        order: 9,
        type: 'quiz',
        question:
          'Что произойдёт, если внутри функции обратиться к переменной, не объявляя её (в strict mode)?',
        options: [
          'Создастся глобальная переменная',
          'Выбросит ReferenceError',
          'Выбросит TypeError',
          'Вернёт undefined',
        ],
        correctIndex: 1,
      },
      {
        id: 20,
        order: 10,
        type: 'quiz',
        question: 'Что означает hoisting (всплытие) в JS?',
        options: [
          'Перемещение объявлений (не инициализаций) в начало области видимости',
          'Автоматическое преобразование типов',
          'Ускорение выполнения циклов',
          'Запрет на использование var',
        ],
        correctIndex: 0,
      },
    ],
  },

  {
    id: 'js-objects-this-prototype',
    title: 'JS Objects: this, Prototype, Classes',
    description: 'Контекст this, методы, bind/call/apply, прототипы и основы классов.',
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSlKGWQNw9SzJsAcQn7gisfnwGESGyS1qyyw&s',
    questionCount: 10,
    questions: [
      {
        id: 21,
        order: 1,
        type: 'quiz',
        question: 'Чему равен this в обычной функции при вызове fn() в strict mode?',
        options: ['window', 'global', 'undefined', 'самой функции fn'],
        correctIndex: 2,
      },
      {
        id: 22,
        order: 2,
        type: 'quiz',
        question: 'Какой метод создаёт новую функцию с навсегда привязанным this?',
        options: ['call', 'apply', 'bind', 'assign'],
        correctIndex: 2,
      },
      {
        id: 23,
        order: 3,
        type: 'quiz',
        question: 'Чем отличается call от apply?',
        options: [
          'call принимает аргументы списком, apply — массивом',
          'apply быстрее, чем call',
          'call работает только с методами объекта',
          'apply нельзя использовать с this',
        ],
        correctIndex: 0,
      },
      {
        id: 24,
        order: 4,
        type: 'quiz',
        question: 'Что такое прототип (prototype) в JS?',
        options: [
          'Механизм наследования через цепочку объектов',
          'Тип данных для функций',
          'Синтаксис для приватных полей',
          'Встроенный модуль Node.js',
        ],
        correctIndex: 0,
      },
      {
        id: 25,
        order: 5,
        type: 'quiz',
        question: 'Где хранится прототип функций-конструкторов?',
        options: [
          'constructor.__proto__',
          'constructor.prototype',
          'object.prototype',
          'Function.__proto__',
        ],
        correctIndex: 1,
      },
      {
        id: 26,
        order: 6,
        type: 'quiz',
        question: 'Что вернёт выражение: ({}) instanceof Object ?',
        options: ['true', 'false', 'TypeError', 'undefined'],
        correctIndex: 0,
      },
      {
        id: 27,
        order: 7,
        type: 'quiz',
        question: 'Как создать объект с прототипом null?',
        options: [
          'new Object(null)',
          'Object.create(null)',
          '{}.create(null)',
          'Object.setPrototypeOf({}, null)',
        ],
        correctIndex: 1,
      },
      {
        id: 28,
        order: 8,
        type: 'quiz',
        question:
          'Что произойдёт при обращении к свойству, которого нет у объекта, но есть в прототипе?',
        options: [
          'Вернёт undefined',
          'Выбросит TypeError',
          'Найдёт свойство по цепочке прототипов',
          'Создаст свойство автоматически',
        ],
        correctIndex: 2,
      },
      {
        id: 29,
        order: 9,
        type: 'quiz',
        question: 'Чем стрелочная функция отличается по this?',
        options: [
          'У стрелочной функции свой this, как у обычной',
          'Стрелочная функция берёт this из внешней области (лексически)',
          'Стрелочная функция всегда привязывается к window',
          'У стрелочной функции this всегда undefined',
        ],
        correctIndex: 1,
      },
      {
        id: 30,
        order: 10,
        type: 'quiz',
        question: 'Что делает оператор new при вызове функции-конструктора?',
        options: [
          'Создаёт объект, связывает его прототип, вызывает функцию с this и возвращает объект',
          'Только вызывает функцию',
          'Создаёт класс в рантайме',
          'Копирует свойства из prototype в объект',
        ],
        correctIndex: 0,
      },
    ],
  },

  {
    id: 'js-arrays-methods',
    title: 'JS Arrays: Methods & Mutation',
    description: 'Методы массивов, мутации, map/filter/reduce, сортировка и сравнение.',
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjSwhVCJ_gVltd2jd559Z2gGUyRMwmC_YCIQ&s',
    questionCount: 10,
    questions: [
      {
        id: 31,
        order: 1,
        type: 'quiz',
        question: 'Какой метод создаёт новый массив, не изменяя исходный?',
        options: ['push', 'splice', 'map', 'sort'],
        correctIndex: 2,
      },
      {
        id: 32,
        order: 2,
        type: 'quiz',
        question: 'Какой метод изменяет исходный массив?',
        options: ['filter', 'concat', 'slice', 'splice'],
        correctIndex: 3,
      },
      {
        id: 33,
        order: 3,
        type: 'quiz',
        question: 'Что вернёт [].length ?',
        options: ['0', 'null', 'undefined', '1'],
        correctIndex: 0,
      },
      {
        id: 34,
        order: 4,
        type: 'quiz',
        question: 'Что вернёт [1,2,3].reduce((acc,x)=>acc+x, 0) ?',
        options: ['6', '3', '0', 'TypeError'],
        correctIndex: 0,
      },
      {
        id: 35,
        order: 5,
        type: 'quiz',
        question: 'Что делает Array.isArray(value)?',
        options: [
          'Проверяет, что value это массив',
          'Преобразует value в массив',
          'Проверяет, что value это объект',
          'Сравнивает два массива',
        ],
        correctIndex: 0,
      },
      {
        id: 36,
        order: 6,
        type: 'quiz',
        question: 'Как правильно отсортировать числа по возрастанию?',
        options: [
          '[10,2,1].sort()',
          '[10,2,1].sort((a,b)=>a-b)',
          '[10,2,1].sort((a,b)=>b-a)',
          '[10,2,1].sort(Number)',
        ],
        correctIndex: 1,
      },
      {
        id: 37,
        order: 7,
        type: 'quiz',
        question: 'Что вернёт [1,2,3].includes(2)?',
        options: ['true', 'false', '2', 'undefined'],
        correctIndex: 0,
      },
      {
        id: 38,
        order: 8,
        type: 'quiz',
        question: 'Чем отличается slice от splice?',
        options: [
          'slice мутирует массив, splice нет',
          'splice мутирует массив и может удалять/вставлять элементы, slice не мутирует и возвращает копию части',
          'slice работает только со строками',
          'splice возвращает индекс, slice возвращает boolean',
        ],
        correctIndex: 1,
      },
      {
        id: 39,
        order: 9,
        type: 'quiz',
        question: 'Что вернёт [1,2,3].find(x => x > 1)?',
        options: ['2', '[2,3]', 'true', '1'],
        correctIndex: 0,
      },
      {
        id: 40,
        order: 10,
        type: 'quiz',
        question: 'Что вернёт [1,2,3].every(x => x > 0)?',
        options: ['true', 'false', '1', 'undefined'],
        correctIndex: 0,
      },
    ],
  },

  {
    id: 'js-async-event-loop',
    title: 'JS Async: Promises & Event Loop',
    description: 'Очереди задач, microtasks/macrotasks, Promises, async/await и таймеры.',
    imageUrl:
      'https://avatars.mds.yandex.net/i?id=4ad92aec5b81d2181fa555dd16d28daf578da1d7-9211697-images-thumbs&n=13',
    questionCount: 10,
    questions: [
      {
        id: 41,
        order: 1,
        type: 'quiz',
        question: 'Что возвращает async функция всегда?',
        options: ['Promise', 'number', 'callback', 'undefined'],
        correctIndex: 0,
      },
      {
        id: 42,
        order: 2,
        type: 'quiz',
        question: 'Какая очередь выполняется раньше: microtasks или macrotasks?',
        options: ['macrotasks', 'microtasks', 'одновременно', 'зависит от браузера'],
        correctIndex: 1,
      },
      {
        id: 43,
        order: 3,
        type: 'quiz',
        question: 'К чему приводит вызов Promise.resolve(5)?',
        options: [
          'Создаёт отклонённый промис',
          'Создаёт промис, который выполнится со значением 5',
          'Блокирует поток',
          'Возвращает 5 без промиса',
        ],
        correctIndex: 1,
      },
      {
        id: 44,
        order: 4,
        type: 'quiz',
        question: 'Что делает await?',
        options: [
          'Останавливает весь JS',
          'Ждёт выполнения промиса внутри async функции',
          'Превращает функцию в синхронную',
          'Отменяет промис',
        ],
        correctIndex: 1,
      },
      {
        id: 45,
        order: 5,
        type: 'quiz',
        question:
          'Что выведет код?\nconsole.log(1); setTimeout(()=>console.log(2),0); console.log(3);',
        options: ['1 2 3', '1 3 2', '2 1 3', '3 1 2'],
        correctIndex: 1,
      },
      {
        id: 46,
        order: 6,
        type: 'quiz',
        question:
          'Что выведет код?\nconsole.log(1); Promise.resolve().then(()=>console.log(2)); console.log(3);',
        options: ['1 2 3', '1 3 2', '2 1 3', '3 1 2'],
        correctIndex: 1,
      },
      {
        id: 47,
        order: 7,
        type: 'quiz',
        question: 'Как поймать ошибку промиса?',
        options: ['.catch()', '.error()', '.fail()', 'try/catch без await'],
        correctIndex: 0,
      },
      {
        id: 48,
        order: 8,
        type: 'quiz',
        question: 'Что делает Promise.all?',
        options: [
          'Возвращает первый выполненный промис',
          'Ждёт выполнения всех промисов или падает на первом reject',
          'Выполняет промисы по очереди',
          'Отменяет все промисы',
        ],
        correctIndex: 1,
      },
      {
        id: 49,
        order: 9,
        type: 'quiz',
        question: 'Что делает Promise.race?',
        options: [
          'Ждёт все промисы',
          'Возвращает результат первого завершившегося промиса (resolve/reject)',
          'Сортирует промисы по времени',
          'Всегда возвращает resolve',
        ],
        correctIndex: 1,
      },
      {
        id: 50,
        order: 10,
        type: 'quiz',
        question: 'Где выполняется .then() колбэк промиса относительно таймера setTimeout(…, 0)?',
        options: [
          'После setTimeout',
          'До setTimeout (microtask раньше macrotask)',
          'Одновременно',
          'Зависит от количества промисов',
        ],
        correctIndex: 1,
      },
    ],
  },
];
